# Generated by Django 5.1.5 on 2025-01-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyhistory',
            name='is_tracked',
        ),
        migrations.AddField(
            model_name='dailyhistory',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
